project_name: spotify-cli

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/spotify-cli
    binary: spotify-cli
    ldflags:
      - -s -w
      - -X github.com/skmatz/spotify-cli/cmd/spotify-cli/cmd.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - 386
      - amd64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      386: i386
      amd64: x86_64

release:
  prerelease: auto
